### ISSUE TITLE
action fails unless actions have write permissions

### ISSUE THREAD

**Issue by whitney** [jwalton/gh-find-current-pr#114]
### Summary
Our org recently upgraded to Github enterprise and found that workflows using this action would fail with a message "Resource not accessible by integration" 

### Version
1.3.0

### Description
The `gh-find-current-pr` action fails when granted read-only access at the Enterprise > policies > actions level. It succeeds when we grant read/write access to Github actions. I cannot think of why this action would need write access.

**Comment by random-donuts** [comment]
just tested, you do not need write, you only need to elevate the permission for `pull-requests: read`

This is what I used for my permission
```
permissions:
  actions: read
  attestations: none
  checks: read
  contents: read
  deployments: read
  id-token: none
  issues: read
  packages: none
  pages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none
```
