### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by David-Lor** [jwalton/gh-find-current-pr#12]
Using the following workflow:

```yaml
on:
  pull_request:
    branches:
      - main
    types:
      - closed

name: Tag on merged PR

jobs:
  tag:
    name: Tag merged MR
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Get PR description
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
      - name: Echo PR data
        run: echo "Number = ${number} | Title = ${title} | Body = ${body}"
        env:
          number: ${{ steps.findPr.outputs.pr }}
          title: ${{ steps.findPr.outputs.title }}
          body: ${{ steps.findPr.outputs.body }}
```

The `steps.findPr.outputs.*` fields return empty.

If I modify the workflow to use the example given in this repository readme, the step does not run, as if it was not triggered by a merged PR. I'm working on a Private repository (for testing purposes), maybe this is not possible with this Action? I tried using the GITHUB_TOKEN, as I saw on the Action source that it was an optional parameter.

```yaml
on:
  push:
    branches:
      - main

name: Tag on merged PR

jobs:
  tag:
    name: Tag merged MR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr
        env:  # tried with "env" and "with"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
```

**Comment by rob-baldwin** [comment]
@David-Lor try:

```
- uses: jwalton/gh-find-current-pr@v1.0.2
  id: findPr
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
```
