### ISSUE TITLE
Action triggered on closed PR does not seem to find the PR number correctly

### ISSUE THREAD

**Issue by spkane** [jwalton/gh-find-current-pr#15]
I am using this in a job that triggers when a PR is closed:

```yaml
on:
  pull_request:
    types: [closed]
```

like this:

```yaml
      - name: Detect Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: all
```

but later, when I use this:

```yaml
        env:
          PR_NUM: ${{ steps.findPr.outputs.pr }}
```

That value is empty...

**Comment by spkane** [comment]
I initially was using

```yaml
      - name: Detect Pull Request
        uses: jwalton/gh-find-current-pr@v1
        id: findPr
        with:
          state: closed
```

But that did not work any differently.
